{
 "title": "MongoDB Dashboard Copy",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Cluster",
    "query": {
     "query": "label_values(mongodb_connections_available, cl_name)"
    }
   }
  ]
 },
 "panels": [
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Uptime (minutes)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "mongodb_uptimeMillis" }
   ]
  },
  {
   "title": "Connections",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "mongodb_connections_available", "legendFormat": "Available" },
    { "expr": "mongodb_connections_active", "legendFormat": "Active" }
   ]
  },
  {
   "title": "Mongo Pods Memory Usage in GB / Total Available on Cluster",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(hardware_system_memory_mem_free_kilobytes{cl_name=~\"$Cluster.*\"})",
     "legendFormat": "Working"
    },
    {
     "expr": "sum(hardware_system_memory_mem_available_kilobytes{cl_name=~\"$Cluster.*\"})",
     "legendFormat": "Available"
    }
   ]
  },
  {
   "title": "Mongo Pods CPU Usage / Total Available on Cluster",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(hardware_system_cpu_user_milliseconds{cl_name=~\"$Cluster.*\"}[5m]))",
     "legendFormat": "Usage"
    },
    {
     "expr": "sum(hardware_platform_num_logical_cpus{cl_name=~\"$Cluster.*\"})",
     "legendFormat": "Available"
    }
   ]
  },
  {
   "title": "Catalog Stats",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(mongodb_catalogStats_collections{cl_name=~\"$Cluster.*\"})",
     "legendFormat": "Collections"
    },
    {
     "expr": "max(mongodb_catalogStats_capped{cl_name=~\"$Cluster.*\"})",
     "legendFormat": "Capped Collections"
    },
    {
     "expr": "max(mongodb_catalogStats_timeseries{cl_name=~\"$Cluster.*\"})",
     "legendFormat": "Timeseries"
    },
    {
     "expr": "max(mongodb_catalogStats_views{cl_name=~\"$Cluster.*\"})",
     "legendFormat": "Views"
    }
   ]
  },
  {
   "title": "Global Locks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(mongodb_globalLock_activeClients_total{cl_name=~\"$Cluster.*\"})",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(mongodb_globalLock_activeClients_readers{cl_name=~\"$Cluster.*\"})",
     "legendFormat": "Readers"
    },
    {
     "expr": "sum(mongodb_globalLock_activeClients_writers{cl_name=~\"$Cluster.*\"})",
     "legendFormat": "Writers"
    }
   ]
  },
  {
   "title": "Cursors",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mongodb_metrics_cursor_open_total{cl_name=~\"$Cluster.*\"}",
     "legendFormat": "{{pod}} Open"
    },
    {
     "expr": "mongodb_metrics_cursor_open_noTimeout{cl_name=~\"$Cluster.*\"}",
     "legendFormat": "{{pod}} Open No Timeout"
    },
    {
     "expr": "mongodb_metrics_cursor_timed_out{cl_name=~\"$Cluster.*\"}",
     "legendFormat": "{{pod}} Timed Out"
    }
   ]
  },
  {
   "title": "Documents",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mongodb_metrics_document_inserted{cl_name=~\"$Cluster.*\"}",
     "legendFormat": "{{pod}} Inserted"
    },
    {
     "expr": "mongodb_metrics_document_returned{cl_name=~\"$Cluster.*\"}",
     "legendFormat": "{{pod}} Returned"
    },
    {
     "expr": "mongodb_metrics_document_deleted{cl_name=~\"$Cluster.*\"}",
     "legendFormat": "{{pod}} Deleted"
    },
    {
     "expr": "mongodb_metrics_document_updated{cl_name=~\"$Cluster.*\"}",
     "legendFormat": "{{pod}} Updated"
    }
   ]
  },
  {
   "title": "Replication Network Usage",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(mongodb_metrics_repl_network_bytes{cl_name=~\"$Cluster.*\"})",
     "legendFormat": "Total Usage"
    }
   ]
  },
  {
   "title": "Replication Operations",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(mongodb_metrics_repl_network_ops{cl_name=~\"$Cluster.*\"})"
    }
   ]
  },
  {
   "title": "Network Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "max(mongodb_network_bytesIn{cl_name=~\"$Cluster.*\"})",
     "legendFormat": "Bytes In"
    },
    {
     "expr": "max(mongodb_network_bytesOut{cl_name=~\"$Cluster.*\"})",
     "legendFormat": "Bytes Out"
    }
   ]
  },
  {
   "title": "Latencies",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "max(mongodb_opLatencies_reads_latency{cl_name=~\"$Cluster.*\"})",
     "legendFormat": "Reads"
    },
    {
     "expr": "max(mongodb_opLatencies_commands_latency{cl_name=~\"$Cluster.*\"})",
     "legendFormat": "Commands"
    },
    {
     "expr": "max(mongodb_opLatencies_transactions_latency{cl_name=~\"$Cluster.*\"})",
     "legendFormat": "Transactions"
    },
    {
     "expr": "max(mongodb_opLatencies_writes_latency{cl_name=~\"$Cluster.*\"})",
     "legendFormat": "Writes"
    }
   ]
  },
  {
   "title": "Ops",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(mongodb_opLatencies_reads_ops{cl_name=~\"$Cluster.*\"})",
     "legendFormat": "Reads"
    },
    {
     "expr": "max(mongodb_opLatencies_commands_ops{cl_name=~\"$Cluster.*\"})",
     "legendFormat": "Commands"
    },
    {
     "expr": "max(mongodb_opLatencies_transactions_ops{cl_name=~\"$Cluster.*\"})",
     "legendFormat": "Transactions"
    },
    {
     "expr": "max(mongodb_opLatencies_writes_ops{cl_name=~\"$Cluster.*\"})",
     "legendFormat": "Writes"
    }
   ]
  }
 ]
}